server:
  port: 9300

spring:
  application:
    name: nacos-rocketmq-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Soldier@53
    url: jdbc:mysql://localhost:3306/demo
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis-plus:
  type-aliases-package: com.example.nacosrocketmqprovider.model

pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql


rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}
    max-message-size: 4096
