server:
  port: 9310

spring:
  application:
    name: nacos-rocketmq-consumer
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis-plus:
  type-aliases-package: com.example.nacosrocketmqconsumer.model

rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}
    max-message-size: 4096